version: '3.3'

services:

  db:
    restart: always
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:3.0

  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile

    command: bash -c "/code/manage.py migrate --noinput && /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file: .env

volumes:
  postgres_data:
